---
theme: jekyll-theme-minimal
title: Jofeth Abello
description: Portfolio, research, and technical blog</br></br>

<strong>Navigation</strong><br>
<a href="/">Home</a><br>
<a href="/projects">Projects</a><br>
<a href="/blog">Blog</a><br><br>

<a href="https://github.com/Baccano01">
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" width="18">
</a><br>
<a href="www.linkedin.com/in/jofethabello">
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" width="18">
</a>

github:
  is_project_page: false
